### ISSUE TITLE
receiving error after activation

### ISSUE THREAD

**Issue by its2fun** [hps/heartland-gravity-forms-addon#4]
After I activated the add-on, I clicked on the Forms menu link, then clicked on a form to edit and received this error:
Warning: include(/home/mamabear/public_html/wp-content/plugins/classes/../gravityforms-securesubmit/templates/client-side-merge-tags.php): failed to open stream: No such file or directory in /home/mamabear/public_html/wp-content/plugins/heartland-gravity-forms-addon-master/classes/class-gf-securesubmit.php on line 627

Warning: include(): Failed opening '/home/mamabear/public_html/wp-content/plugins/classes/../gravityforms-securesubmit/templates/client-side-merge-tags.php' for inclusion (include_path='.:/opt/php54/lib/php') in /home/mamabear/public_html/wp-content/plugins/heartland-gravity-forms-addon-master/classes/class-gf-securesubmit.php on line 627

**Comment by slogsdon** [comment]
@its2fun It looks like there is an issue with how we are pulling the plugin directory to load those files. I'll work on a fix for this and report back.

**Comment by slogsdon** [comment]
@its2fun We just merge in the fix for this. Would you mind checking it out and seeing if it resolves your issue?

**Comment by its2fun** [comment]
This is resolved. Thanks!
